### ISSUE TITLE
hi,  I met some mistakes

### ISSUE THREAD

**Issue by vTNT** [ptonini/battuta-manager#1]
[28/Jan/2016 08:17:53] "POST /runner/adhoc/ HTTP/1.1" 200 2
Internal Server Error: /inventory/group/1/variable/list_inh/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/battuta-manager/battuta/inventory/views.py", line 97, in get
    group_all = Group.objects.get(name='all')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
DoesNotExist: Group matching query does not exist.
[28/Jan/2016 08:17:53] "GET /inventory/group/1/variable/list_inh/?_=1453969073532 HTTP/1.1" 500 13300

**Comment by vTNT** [comment]
i use mysql
